### ISSUE TITLE
How to use the provided service from consuming application

### ISSUE THREAD

**Issue by mockuniverse** [bersling/angular-library-example#1]
Most examples also skip over importing and using the service and it's not clear how to accomplish that (elegantly) from an imported module.  

Say we have a module exposing a service:

`
static forRoot() : ModuleWithProviders { 
    return { 
        ngModule: MyModule, 
        providers: [MyService] 
    } 
} 
`
Now we can publish, then install, then use add this module to our application: 

`imports [ MyModule.forRoot() ...]`

But how does the application access MyService? I assumed this would work but it doesn't: 

`import { MyService } from 'MyModule  // doesn't work, there's no MyService exported`

Do we really have to path to the MyService typescript file under the installed package in node_modules/MyModule/... ???

Every example I've seen omits this step of actually importing and invoking the service from an imported NgModule.  Can you shed any light on that?

**Comment by bersling** [comment]
I've added an example consumer, does that solve your issue?
